### ISSUE TITLE
train.lua --dataset parameter doesn't seem to be working

### ISSUE THREAD

**Issue by maraoz** [macournoyer/neuralconvo#10]
Whatever I pass to it, it always loads 221282 examples, and takes ~5 hours to train 1 epoch.

**Comment by macournoyer** [comment]
Can you paste the full command you're running?

**Comment by maraoz** [comment]
Sure. For example:

`th train.lua --cuda --dataset 1 --hiddenSize 256`
and got:
```
-- Loading dataset
Loading vocabulary from data/vocab.t7 ...

Dataset stats:
  Vocabulary size: 35147
         Examples: 221282                                                   
-- Epoch 1 / 50
...
```

**Comment by siddBanPsu** [comment]
@maraoz  Delete the *.t7 files from the data directory. They are generated when the code runs and the vocab and examples are possibly never recreated. Otherwise, you can modify the code to overwrite the file everytime.

**Comment by macournoyer** [comment]
Pretty sure that's it. Nice catch @siddBanPsu!
