### ISSUE TITLE
sizes do not match

### ISSUE THREAD

**Issue by flybirp** [macournoyer/neuralconvo#17]
zhangtekiMacBook-Air:lua_seq2seq zhangx$ th train.lua --opencl --dataset 5000 --hiddenSize 1000
libthclnn_searchpath	/Users/zhangx/torch/install/lib/lua/5.1/libTHCLNN.so	
-- Loading dataset	
Loading vocabulary from data/vocab.t7 ...	

Dataset stats:	
  Vocabulary size: 7061	
         Examples: 8151	
Using Apple , OpenCL platform: Apple
Using OpenCL device: HD Graphics 5000

-- Epoch 1 / 50	
	
/Users/zhangx/torch/install/bin/luajit: /Users/zhangx/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 3 module of nn.Sequential:
...hangx/torch/install/share/lua/5.1/rnn/recursiveUtils.lua:57: bad argument #2 to 'add' (sizes do not match at /tmp/luarocks_cltorch-scm-1-387/cltorch/cltorch/src/lib/THClTensorMathPointwise.cpp:156)
stack traceback:
	[C]: in function 'add'
	...hangx/torch/install/share/lua/5.1/rnn/recursiveUtils.lua:57: in function 'recursiveAdd'
	/Users/zhangx/torch/install/share/lua/5.1/rnn/LSTM.lua:192: in function '_updateGradInput'
	...gx/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:57: in function 'updateGradInput'
	/Users/zhangx/torch/install/share/lua/5.1/rnn/Sequencer.lua:79: in function 'updateGradInput'
	/Users/zhangx/torch/install/share/lua/5.1/nn/Module.lua:31: in function </Users/zhangx/torch/install/share/lua/5.1/nn/Module.lua:29>
	[C]: in function 'xpcall'
	/Users/zhangx/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/Users/zhangx/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./seq2seq.lua:90: in function 'train'
	train.lua:85: in main chunk
	[C]: in function 'dofile'
	...angx/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0109d61d10

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/Users/zhangx/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/Users/zhangx/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./seq2seq.lua:90: in function 'train'
	train.lua:85: in main chunk
	[C]: in function 'dofile'
	...angx/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0109d61d10

**Comment by iceboal** [comment]
I have exact the same error while training with OpenCL. With CUDA, I got:
```
Dataset stats:	
  Vocabulary size: 7061	
         Examples: 8151	

-- Epoch 1 / 50	
	
[1]    15512 segmentation fault (core dumped)  th train.lua --cuda --dataset 5000 --hiddenSize 1000
```

**Comment by jamesweb1** [comment]
I have the same platform as yours, and I got the same error. But it works well on my another ubuntu PC with nvidia 980.

**Comment by jamesweb1** [comment]
I found the issue is from the latest module of 'nn'. When you install this module these days, it will not compatible of this project and produce the error we see. 

You can wait for the author to fix it, or see the commit of module 'nn'. The website is [torch-nn](https://github.com/torch/nn). 

The bad news is luarocks doesn't do well on the version control. You cannot install the older version simply, because the version of 'nn' is **scm-1** and it is still  **scm-1** after minor updates.

**Comment by iceboal** [comment]
Thanks, @jamesweb1 , I made it working by overriding the nn module with commit e11516e (just picked a random commit which is several days ago). Path:

    ~/torch/install/share/lua/5.1/nn

**Comment by vikram-gupta** [comment]
Thanks @iceboal for the suggestion. Wanted to confirm that i was also able to run after overriding nn module.

@iceboal Did you investigate the breaking commits? I think it would be ideal to use the latest "nn" versions.

**Comment by spro** [comment]
Overriding nn did not work for me, but this change did:

```diff
   -- Forward pass
-  self.encoder:forward(encoderInput)
+  local encoderOutput = self.encoder:forward(encoderInput)
   self:forwardConnect(encoderInput:size(1))
   local decoderOutput = self.decoder:forward(decoderInput)
   local Edecoder = self.criterion:forward(decoderOutput, decoderTarget)
@@ -87,7 +77,7 @@ function Seq2Seq:train(input, target)
   local gEdec = self.criterion:backward(decoderOutput, decoderTarget)
   self.decoder:backward(decoderInput, gEdec)
   self:backwardConnect()
-  self.encoder:backward(encoderInput, self.zeroTensor)
+  self.encoder:backward(encoderInput, encoderOutput:zero())
```
