### ISSUE TITLE
weird result I got when I train the model for myself

### ISSUE THREAD

**Issue by jamesweb1** [macournoyer/neuralconvo#18]
I try to reproduce the experiments result from the paper, and I use your code as test. But the result seems to be very strange. Following is my command and settings:
`th train.lua --cuda --dataset 50000 --hiddenSize 1000`
I use the default settings in the project, and expand the dataset from 5000 to 50000. The dataset of 50000 seems to be worse than 5000, and this makes me confuse. I run for 50 epochs, and the last log is:
```
-- Epoch 50 / 50	
[================================ 83632/83632 =======================>]  Tot: 1h35m | Step: 68ms
Finished in 1h35m 14.664488722944 examples/sec.
Epoch stats:
           LR= 1e-05	
  Errors: min= 3.814697265625e-06	
          max= 67.265952110291	
       median= 6.5410537719727	
         mean= 7.5180888369819	
          std= 5.9302086321892	
```

After training, I use `th -i eval.lua --cuda` to see the ability of my model:
```
th> say 'Hi'
>> Hi walter really, sorry, sorry, sorry, sorry, sorry, sorry, sorry, sorry,	
                                                                      [0.0347s]	
th> say 'what\'s your name ?'
>> De fravio if it says who me more in your money first of mother, the place.	
                                                                      [0.0346s]	
th> say 'how old are you ?'
>> Twelve way right now.	
                                                                      [0.0122s]	
th> say 'what\'s 2 + 2 ?'
>> One.	
                                                                      [0.0111s]	
th> say 'how are you'
>> I'look here but it'look here but it'look here but it'look here but	
                                                                      [0.0347s]	
th> say 'good bye'
>> That don ?...
```

The result show almost no response is understandable by human without the logic and grammar. Anything I didn't catch to get this result? Please give me some hint on that. Thanks a lot.

**Comment by keerthiskating** [comment]
Did the results improve anything now ? Also if you are looking for Conversational Models, here's one [](https://github.com/isi-nlp/Zoph_RNN). Do let me know if you are able to achieve something better on this   .

**Comment by jamesweb1** [comment]
It seems to be difficult to feed the dataset in this project to your Zoph_RNN. Do you give it a try and show some results?

**Comment by keerthiskating** [comment]
In the [current work](https://github.com/macournoyer/neuralconvo) cornell dataset is well handled. That makes this work specific to cornell dataset is what I understnad. But where as in Zoph_RNN you can feed it with any dataset. Execute `./RNN_MODEL -h` and you'll know how to play with it. Also feeding the data is simple. You train the network providing two main arguments - source file and target file.
Source file has sentence uttered by speaker 1
Target file has sentence uttered by speaker 2

**Comment by jamesweb1** [comment]
Do you mean I should parse the cornell dataset to 2 files (Source file and Target file), and then feed it to your project?

**Comment by keerthiskating** [comment]
@jamesweb1 First thing it's not my project :p . And yes it should be fed as 2 files.

**Comment by jamesweb1** [comment]
@keerthiskating Hi, I train my model in the project Zoph_RNN. But how can I evaluate my model there? I train the seq-seq model, but I don't know how can I input a sentence and get the predicted output sentence in that project. Do you give it a try?

**Comment by keerthiskating** [comment]
@jamesweb1 The only metric available is Perplexity, though it's not accurate. I've been working on this. Mail me : keerthimanu@multicorewareinc.com

**Comment by spro** [comment]
Here's potential fix for the repetative output issue: https://github.com/macournoyer/neuralconvo/pull/25

**Comment by jamesweb1** [comment]
@spro I've tested with your code. And it indeed gives the better response :D

BTW, I still want to know how to get the better parameters.
