### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sujitahirrao** [macournoyer/neuralconvo#20]
After successful installation of Torch and dependencies, I started training with `th train.lua --cuda --dataset 5000 --hiddenSize 1000` 

and I got this in my terminal

![seg_fault_torch](https://cloud.githubusercontent.com/assets/13721140/14809493/1e4b6736-0bab-11e6-871c-c81ee9316b80.png)
 
If anyone needs more information, please comment.

**Comment by sujitahirrao** [comment]
Update:

I changes the flag from --cuda to --opencl and got this:
`-- Loading dataset	
Loading vocabulary from data/vocab.t7 ...	

Dataset stats:	
  Vocabulary size: 7061	
         Examples: 8151	
Using NVIDIA Corporation , OpenCL platform: NVIDIA CUDA
Using OpenCL device: GeForce 820M

-- Epoch 1 / 50	
	
/home/sujit/torch/install/bin/luajit: /home/sujit/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 3 module of nn.Sequential:
...sujit/torch/install/share/lua/5.1/rnn/recursiveUtils.lua:57: bad argument #2 to 'add' (sizes do not match at /tmp/luarocks_cltorch-scm-1-2933/cltorch/cltorch/src/lib/THClTensorMathPointwise.cpp:156)
stack traceback:
	[C]: in function 'add'
	...sujit/torch/install/share/lua/5.1/rnn/recursiveUtils.lua:57: in function 'recursiveAdd'
	/home/sujit/torch/install/share/lua/5.1/rnn/LSTM.lua:192: in function '_updateGradInput'
	...it/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:58: in function 'updateGradInput'
	/home/sujit/torch/install/share/lua/5.1/rnn/Sequencer.lua:79: in function 'updateGradInput'
	/home/sujit/torch/install/share/lua/5.1/nn/Module.lua:31: in function </home/sujit/torch/install/share/lua/5.1/nn/Module.lua:29>
	[C]: in function 'xpcall'
	/home/sujit/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/sujit/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./seq2seq.lua:90: in function 'train'
	train.lua:85: in main chunk
	[C]: in function 'dofile'
	...ujit/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/sujit/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/sujit/torch/install/share/lua/5.1/nn/Sequential.lua:84: in function 'backward'
	./seq2seq.lua:90: in function 'train'
	train.lua:85: in main chunk
	[C]: in function 'dofile'
	...ujit/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
`

**Comment by keerthiskating** [comment]
I executed this command : 
`th train.lua --cuda --dataset 5000 --hiddenSize 1000` and got this 
/home/torch/install/bin/luajit: /home/mcw/torch/install/share/lua/5.1/trepl/init.lua:363: /home/torch/install/share/lua/5.1/trepl/init.lua:363: /home/torch/install/share/lua/5.1/trepl/init.lua:363: /home/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
	[C]: in function 'error'
	/home/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
	train.lua:1: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406670

**Comment by macournoyer** [comment]
I think that's because your graphic card doesn't have enough memory to fix the data ... hard to tell

Can you try w/ latest master, it fixes a few other things.
