### ISSUE TITLE
attempt to call field 'TestSuite' (a nil value)

### ISSUE THREAD

**Issue by tdaseed** [macournoyer/neuralconvo#22]
Hi lua/torch newbie here,

I followed the installation in https://github.com/hughperkins/distro-cl as I couldn't get cltorch installed using the official way, and now seemingly everything is in place but I can run any of the lua scripts and keep getting:

attempt to call field 'TestSuite' (a nil value)

Help please.

Tan

**Comment by macournoyer** [comment]
Do you have a full traceback?
