### ISSUE TITLE
"cltorch" and "clnn" required even when running with "--cuda"

### ISSUE THREAD

**Issue by vikram-gupta** [macournoyer/neuralconvo#23]
I am running the training module using using "--cuda" parameter. 

`th train.lua --cuda --dataset 5000 --hiddenSize 100`

But since, the file "neuralconvo.lua" requires "cltorch" and "clnn", the training fails. Is this intended? Can we safely remove the requirement for "cltorch" and "clnn" from "neuralconvo.lua" ?

**Comment by macournoyer** [comment]
#25 should fix this
