### ISSUE TITLE
Mini-batch learning

### ISSUE THREAD

**Issue by chenb67** [macournoyer/neuralconvo#27]
Hi,

Cool project!
I looked in the training code and it seems like the model parameters are updated after every example. i.e. online learning.
Is it by design? we can probably achieve a significant speedup by using mini-batches.

**Comment by macournoyer** [comment]
I'd have to re-read the papers, but you think seq2seq will work with batches?

**Comment by chenb67** [comment]
In the original seq2seq paper[1] they use mini-batches of 128(section 3.4).
I guess the best way to know will be to test it, I'll work on it and make a pull request.

[1] https://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf

**Comment by macournoyer** [comment]
Awesome! Thx. Can't wait to see this.
