### ISSUE TITLE
Parameter updation happening after every training example

### ISSUE THREAD

**Issue by vikram-gupta** [macournoyer/neuralconvo#33]
Hi @macournoyer 

We are dividing the training examples into mini-batches while training. However, it looks like that we are updating the parameters of the network after every training example. 

```
self.encoder:updateGradParameters(self.momentum)
self.decoder:updateGradParameters(self.momentum)
self.decoder:updateParameters(self.learningRate)
self.encoder:updateParameters(self.learningRate)
self.encoder:zeroGradParameters()
self.decoder:zeroGradParameters()
```
Are we intentionally doing some kind of online training ? I guess we can average the gradients over all the samples of a mini-batch and then update the parameters?

Thanks,
Vikram

**Comment by macournoyer** [comment]
Check out #29

**Comment by vikram-gupta** [comment]
Thanks @macournoyer
