### ISSUE TITLE
Multiple layers support

### ISSUE THREAD

**Issue by vikram-gupta** [macournoyer/neuralconvo#34]
Do we have a plan to support multiple layers of LSTM ? The paper seems to have used multiple layers in encoder and decoder.

**Comment by macournoyer** [comment]
I'd like to. But ATM I run into memory errors when trying this. Not sure if it's the data or the model causing problems yet...

**Comment by vikram-gupta** [comment]
Hi @macournoyer 

Is there a branch where you committed the code changes for multiple layer support? If yes, i can try to work on it and get back if if the out of memory issue gets resolved.

Thanks,
Vikram

**Comment by macournoyer** [comment]
No branch @vikram-gupta. I just added a line here: https://github.com/macournoyer/neuralconvo/blob/master/seq2seq.lua#L14

**Comment by chenb67** [comment]
@vikram-gupta 
I have multi-layer working on https://github.com/chenb67/neuralconvo/tree/b32fb1725b9977c1933bd4ec7669cc958cca3c18
I'd be happy to have some help testing it..
number of layers is controlled by the flag --numLayers

**Comment by vikram-gupta** [comment]
@chenb67 Surely !

**Comment by macournoyer** [comment]
Currently testing this out in #38
