### ISSUE TITLE
No CUDA capable device is detected

### ISSUE THREAD

**Issue by VibhuSrivastava** [macournoyer/neuralconvo#37]
I am running this on a google cloud linux instance (Ubuntu 14.04 trusty LTS)

When I start training of CPU only, it is running fine.
I have installed CUDA (7.5) and cuDNN(v5.1 RC) and have followed the given instructions:

- Install Torch.
- luarocks install nn
- luarocks install rnn
- luarocks install penlight
- luarocks install cutorch
- luarocks install cunn

However, when I start training with the help of GPU support, I am receiving the following error:

user1@instance-1:~/neuralconvo$ th train.lua --cuda
-- Loading dataset
Loading vocabulary from data/vocab.t7 ...
Dataset stats:
  Vocabulary size: 35147
         Examples: 221282
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-515/cutorch/lib/THC/THCGeneral.c line=20 error=38 : no CUDA-
capable device is detected
/home/user1/torch/install/bin/luajit: ...user1/torch/install/share/lua/5.1/trepl/init.lua:384:
 cuda runtime error (38) : no CUDA-capable device is detected at /tmp/luarocks_cutorch-scm-1-515/cutorch/lib/T
HC/THCGeneral.c:20
stack traceback:
        [C]: in function 'error'
        ...user1/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
        train.lua:55: in main chunk
        [C]: in function 'dofile'
        ...dita/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

What is going wrong and how can I fix this?

**Comment by vikram-gupta** [comment]
Hey @VibhuSrivastava ,

Were you able to build and run the CUDA samples? What is the output of nvidia-smi?
