### ISSUE TITLE
Problems with running the code

### ISSUE THREAD

**Issue by nabihach** [macournoyer/neuralconvo#45]
I am new to Torch and to Lua. I tried to run your code with the following command:

`th train.lua --dataset 10000 --hiddenSize 128`

But I got the following error:

`-- Loading dataset	
data/vocab.t7 not found	
-- Parsing Cornell movie dialogs data set ...	
/home/username/torch/install/bin/luajit: ./cornell_movie_dialogs.lua:49: table index is nil
stack traceback:
	./cornell_movie_dialogs.lua:49: in function 'load'
	./dataset.lua:55: in function 'load'
	./dataset.lua:37: in function '__init'
	/home/username/torch/install/share/lua/5.1/torch/init.lua:91: in function </home/username/torch/install/share/lua/5.1/torch/init.lua:87>
	[C]: in function 'DataSet'
	train.lua:29: in main chunk
	[C]: in function 'dofile'
	...rname/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50
`

How do I resolve this?

**Comment by nabihach** [comment]
Nevermind! I didn't extract the dataset properly, which caused this problem. Closing this thread now.

**Comment by dimeldo** [comment]
Hey @nabihach, can you share your results?

**Comment by nabihach** [comment]
With `th train.lua --dataset 50000 --hiddenSize 128` 
I got the following results after 9 epochs (i am using CPU so each epoch took about 4 hours to run):

`Epoch stats:	
  Errors: min= 2.5786041785935	
          max= 21.767158441141	
       median= 6.4926095234102	
         mean= 6.8780553152687	
          std= 2.2374831136643	
          ppl= 970.73674610767	

`

Running `th eval.lua` gives me the following results:

`	
you> hello
neuralconvo> You're right.	
you> what's up with you
neuralconvo> I'm not a good man.	
you> i am feeling cold
neuralconvo> Yeah, i'm afraid i'll be able to get a good job.	
you> are you a bot
neuralconvo> No.	
you> what do you do
neuralconvo> I'm not a good one.	
you> what do you do
neuralconvo> I'm not going to be a good idea.	
you> why are you talking to me
neuralconvo> You're not.	`
