### ISSUE TITLE
Not enough memory?

### ISSUE THREAD

**Issue by llSourcell** [macournoyer/neuralconvo#5]
I ran this on the CPU for a few hours and when saving the model after training I got an error. Any fix ideas? I'm running this on a macbook with 16 GB of RAM

```bash
1482-sraval:neuralconvo-master sraval$ th train.lua --dataset 5000 --hiddenSize 1000
-- Loading dataset	
Loading vocabulary from data/vocab.t7 ...	

Dataset stats:	
  Vocabulary size: 7061	
         Examples: 8151	

-- Epoch 1 / 50	
	
 [=========================================== 8151/8151 h43m | Step: 690ms      

Finished in 1h43m 1.3066972012208 examples/sec.	

Epoch stats:	
           LR= 0.05	
  Errors: min= 1.1344377487802	
          max= 204.85985171145	
       median= 25.911087689104	
         mean= 33.523359973026	
          std= 27.159547015804	

(Saving model ...)	
/Users/sraval/torch/install/bin/luajit: not enough memory
```

**Comment by macournoyer** [comment]
That is weird... I think 16 GB is enough. Are you using lots of RAM for other apps at the same time?

Also, if your MBP is recent, you should be able to setup CUDA which will reduce training time to ~10min per epoch and might help w/ mem issue.

**Comment by kalloc** [comment]
I'm thinking this error from CUDA ( MBPr NVIDIA doesn't have enough memory)

**Comment by macournoyer** [comment]
Are you using your computer for other things while this is running?
