### ISSUE TITLE
Train in another language

### ISSUE THREAD

**Issue by rmazitov** [macournoyer/neuralconvo#50]
I want to give training to the text in another language.
What files are needed and in what format?

**Comment by nabihach** [comment]
You can modify the script cornell_movie_dialogs.lua to accept the data in any format, and then pre-process. In particular, you need to modify the function function CornellMovieDialogs:load() so that it returns 'conversations', a table of the following form:

**Comment by rmazitov** [comment]
Table what form?

**Comment by nabihach** [comment]
I edited my answer. Please see above.

**Comment by rmazitov** [comment]
Thanks!
