### ISSUE TITLE
Invalid arguments: DoubleTensor number FloatTensor

### ISSUE THREAD

**Issue by julien-c** [macournoyer/neuralconvo#52]
I'm moderately convinced that this is a `neuralconvo` issue per se, but in case it is:

```
/root/torch/install/share/lua/5.1/optim/adam.lua:59: invalid arguments: DoubleTensor number FloatTensor 
expected arguments: *DoubleTensor* [DoubleTensor] double | *DoubleTensor* [DoubleTensor] [double] DoubleTensor
stack traceback:
	[C]: in function 'add'
	/root/torch/install/share/lua/5.1/optim/adam.lua:59: in function 'adam'
	train.lua:131: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50
```

Any idea?

**Comment by zhaopku** [comment]
I have the same problem. Did you train this on CPU? I think this may be a problem of CPU/GPU converting, the author writes the code for GPU but didn't adjust well for CPU. Have a look at this link:
[sample.lua fails to run: error in function addmm()](https://github.com/karpathy/char-rnn/issues/21)

**Comment by zhaopku** [comment]
Problem solved!
Add this function to **seq2seq.lua**:

```
-- function Seq2Seq:double()
-- created by zhaopku to fix the problem of CPU mode
function Seq2Seq:double()
  self.encoder:double()
  self.decoder:double()

  if self.criterion then
    self.criterion:double()
  end
end

```
Then in **train.lua**:

at line 161:
change 
`model:float()`
to 
`model:double()`

**Comment by macournoyer** [comment]
Thx @zhaopku !

**Comment by julien-c** [comment]
Thanks guys! Would it make sense to merge this to the codebase?

**Comment by Cona19** [comment]
Thanks! It works for me!

**Comment by gravitymonkey** [comment]
Thanks, also works for me.  Makes sense to merge (why not?)

**Comment by paularmand** [comment]
yes, working here too. 
+1 for merge
