### ISSUE TITLE
Resume training from a saved model

### ISSUE THREAD

**Issue by nabihach** [macournoyer/neuralconvo#55]
Is there a way to resume training from where it was previously left off? For example, I trained a particular model for 50 epochs and saved it to model.t7. I tested it using eval.lua and discovered that it needed training for another 50 epochs. Is there an easy way for me to resume training such that the model is initialized with model.t7 and then continues to train?

**Comment by macournoyer** [comment]
Not at the moment, but it should be possible to implement relatively easily in train.lua:

Replace the line that [initializes the model](https://github.com/macournoyer/neuralconvo/blob/master/train.lua#L41) w/ code that loads it from the .t7 file (like in eval.lua).

But the epoch count will count back from 1...

**Comment by nabihach** [comment]
Thanks. It turns out that it is also possible to resume training on a different dataset this way.
