### ISSUE TITLE
The lines are shortened to the first sentence

### ISSUE THREAD

**Issue by kenyeung128** [macournoyer/neuralconvo#68]
Hi,
In the description, it said "The lines are shortened to the first sentence", what does it mean to first sentence? is there cases not shortened? Thanks.

In this experiment, we train the seq2seq model with movie dialogs from the Cornell Movie-Dialogs Corpus. The lines are shortened to the first sentence.

**Comment by macournoyer** [comment]
Here's a line from the dataset:

> Can we make this quick?  Roxanne Korrine and Andrew Barrett are having an incredibly horrendous public break- up on the quad.  Again.

We train with "Can we make this quick?" dropping the rest.

**Comment by kenyeung128** [comment]
I see, what would be the approaches if i would like longer sentences? thanks.
