### ISSUE TITLE
Anyone please share their model ?

### ISSUE THREAD

**Issue by kenkit** [macournoyer/neuralconvo#77]
I have a telegram bot @the_eleventh_bot which is currently linked to Program-O aiml bot which is not that intelligent.
I wish someone could just share a trained model which is loadable without a gpu. To do this, just load the model the trained model in torch  then convert it into a cpu model  `model = model:float()  ` 
Anyone can contribute provided they trained on the full dataset.

**Comment by kenkit** [comment]
or just any model I could try and figure a way of converting it myself

**Comment by TTN-** [comment]
I've been trying to get a gpu setup running on my machine for a while now. If I get it going and then get some good results, I'll post a dropbox link with some trained data.

**Comment by TTN-** [comment]
no point opening a duplicate issue when there already is one that is open. You are aware that there is a duplicate issue. Please join the discussion there instead. Cheers :-)
https://github.com/macournoyer/neuralconvo/issues/59

**Comment by kenkit** [comment]
sorry, I had already opened it , I figured that out later.
