### ISSUE TITLE
'unknown object' error when I tried to load examples.t7

### ISSUE THREAD

**Issue by gmkim90** [macournoyer/neuralconvo#8]
First of all, thanks to share your neural conversational model implementation.

I want to see inside of 'examples' variable in your source code.
Specifically, I want to ask solution for error when I tried to load 'examples.t7' written by your code.

As a prerequisite of loading 'examples.t7' in torch7 interactive mode, I first typed
       require 'neuralconvo'
       require 'cutorch'

Then, I typed 
      examples = torch.load('data/examples.t7')
and the following error occurred.

/home/kenkim/torch/install/share/lua/5.1/torch/File.lua:294: unknown object.

Any suggestion to see inside of examples variable?

**Comment by macournoyer** [comment]
`examples.t7` is written in chunks, so you can't load it w/ `torch.load`. Instead you can use the following code:

```lua
local dataset = neuralconvo.DataSet(neuralconvo.CornellMovieDialogs("data/cornell_movie_dialogs"))

for examples in dataset:batches(100) do -- Loads in chunks of 100 examples
  for _, example in ipairs(examples) do

      local input, target = unpack(example)
      -- inspect input and target here ...

  end
end
```

I hope this helps!
