### ISSUE TITLE
training_fail_/seq2seq.lua:62: attempt to call field 'recursiveCopy'

### ISSUE THREAD

**Issue by ArashHosseini** [macournoyer/neuralconvo#80]
@neuralconvo is running on two other machines with cuda and opencl without any probelm.....NOW i setup a fresh os with 14.04, cuda8 and changed cudnn5 to 6 because of tf1.3....torch install done...

trace:

`$ th train.lua --cuda --dataset 5000 --hiddenSize 100-- Loading dataset	
data/vocab.t7 not found	
-- Parsing Cornell movie dialogs data set ...	
 [==================== 387810/387810 ==========>]  Tot: 1s238ms | Step: 0ms     
-- Pre-processing data	
 [==================== 5000/5000 ==============>]  Tot: 771ms | Step: 0ms       
-- Shuffling 	
Writing data/examples.t7 ...	
 [==================== 8151/8151 ==============>]  Tot: 703ms | Step: 0ms       
Writing data/vocab.t7 ...	

Dataset stats:	
  Vocabulary size: 7061	
         Examples: 8151	

-- Epoch 1 / 50  (LR= 0.001)	
	
~/torch/install/bin/luajit: ./seq2seq.lua:62: attempt to call field 'recursiveCopy' (a nil value)
stack traceback:
	./seq2seq.lua:62: in function 'forwardConnect'
	train.lua:97: in function 'opfunc'
	/home/flyn/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
	train.lua:131: in main chunk
	[C]: in function 'dofile'
	...flyn/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
`
never hit this issue before and cant find related details on web, thanks for help

**Comment by ArashHosseini** [comment]
i followed the solution in post #79 and it works now, BUT WHY? i never saw this issue in further training with own or cornell dataset....

```
--[[ Forward coupling: Copy encoder cell and output to decoder LSTM ]]--
function Seq2Seq:forwardConnect(inputSeqLen)
  if (self.decoderLSTM.userPrevOutput ~= nil) then
    self.decoderLSTM.userPrevOutput =
      nn.rnn.recursiveCopy(self.decoderLSTM.userPrevOutput, self.encoderLSTM.outputs[inputSeqLen])
  end
  if (self.decoderLSTM.userPrevCell ~= nil) then
    self.decoderLSTM.userPrevCell =
      nn.rnn.recursiveCopy(self.decoderLSTM.userPrevCell, self.encoderLSTM.cells[inputSeqLen])
  end
end
```

**Comment by hit-lacus** [comment]
I have  same problem.

**Comment by ArashHosseini** [comment]
i talked with marc about that point, he will look into soonish........can you post your env settings, cuda and cudnn version please

**Comment by hit-lacus** [comment]
@ArashHosseini  Are you talk to me?You want me to give my lib version? I am not sure.

**Comment by ArashHosseini** [comment]
@hit-lacus there is no other participant yet. yeah please

**Comment by hit-lacus** [comment]
@ArashHosseini  OK. I am a newbie on deep learning, so I have not enough background knowledge. I was running it on my MacBook Pro.I was using newest version of torch(I installed it one hour ago). And I am not familiar with cudnn right now.
The following is my output:

`
/Users/lacus/torch/install/bin/luajit: /Users/lacus/torch/install/share/lua/5.1/trepl/init.lua:389: /Users/lacus/torch/install/share/lua/5.1/trepl/init.lua:389: module 'nn' not found:No LuaRocks module found for nn
        no field package.preload['nn']
        no file '/Users/lacus/.luarocks/share/lua/5.1/nn.lua'
        no file '/Users/lacus/.luarocks/share/lua/5.1/nn/init.lua'
        no file '/Users/lacus/torch/install/share/lua/5.1/nn.lua'
        no file '/Users/lacus/torch/install/share/lua/5.1/nn/init.lua'
        no file './nn.lua'
        no file '/Users/lacus/torch/install/share/luajit-2.1.0-beta1/nn.lua'
        no file '/usr/local/share/lua/5.1/nn.lua'
        no file '/usr/local/share/lua/5.1/nn/init.lua'
        no file '/Users/lacus/.luarocks/lib/lua/5.1/nn.so'
        no file '/Users/lacus/torch/install/lib/lua/5.1/nn.so'
        no file '/Users/lacus/torch/install/lib/nn.dylib'
        no file './nn.so'
        no file '/usr/local/lib/lua/5.1/nn.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /Users/lacus/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
        train.lua:1: in main chunk
        [C]: in function 'dofile'
        ...acus/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x0103465eb0
`

**Comment by hit-lacus** [comment]
Output:

`
☁  neuralconvo [master] ⚡ th train.lua  
-- Loading dataset      
data/vocab.t7 not found 
-- Parsing Cornell movie dialogs data set ...   
 [======================================== 387810/387810 ==============================>]  Tot: 2s155ms | Step: 0ms     
-- Pre-processing data  
 [======================================== 166194/166194 ==============================>]  Tot: 1m19s | Step: 0ms       
-- Shuffling    
Writing data/examples.t7 ...    
 [======================================== 221282/221282 ==============================>]  Tot: 1m23s | Step: 0ms       
Writing data/vocab.t7 ...       

Dataset stats:  
  Vocabulary size: 35147        
         Examples: 221282       

-- Epoch 1 / 50  (LR= 0.001)    
        
/Users/lacus/torch/install/bin/luajit: ./seq2seq.lua:62: attempt to call field 'recursiveCopy' (a nil value)
stack traceback:
        ./seq2seq.lua:62: in function 'forwardConnect'
        train.lua:97: in function 'opfunc'
        /Users/lacus/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
        train.lua:131: in main chunk
        [C]: in function 'dofile'
        ...acus/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x010f32feb0

`

**Comment by shrutiphadke** [comment]
I have the same problem. Exact same error. I am using Torch without Cuda/OpenCL on Ubuntu 16.04.

**Comment by baaleze** [comment]
It looks like the way to call `recursiveCopy` has changed.
In the file `seq2seq.lua` line 62 & 64 if I replace `nn.rnn.recursiveCopy` by `nn.utils.recursiveCopy` it works for me.
Hope that can help.

**Comment by ArashHosseini** [comment]
perfectly, can also confirm

**Comment by ArashHosseini** [comment]
@baaleze, thx again, did you also got on eval after training?

```
Loading vocabulary from data/vocab.t7 ...	
-- Loading model	

Type a sentence and hit enter to submit.	
CTRL+C then enter to quit.
	
you> hello
/home/flyn/torch/install/bin/luajit: /home/flyn/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 3 module of nn.Sequential:
/home/flyn/torch/install/share/lua/5.1/torch/Tensor.lua:466: Wrong size for view. Input size: 1000. Output size: 25931
stack traceback:
	[C]: in function 'error'
	/home/flyn/torch/install/share/lua/5.1/torch/Tensor.lua:466: in function 'view'
	/home/flyn/torch/install/share/lua/5.1/rnn/utils.lua:191: in function 'recursiveZeroMask'
	/home/flyn/torch/install/share/lua/5.1/rnn/MaskZero.lua:37: in function 'updateOutput'
	/home/flyn/torch/install/share/lua/5.1/rnn/Recursor.lua:13: in function '_updateOutput'
	...yn/torch/install/share/lua/5.1/rnn/AbstractRecurrent.lua:50: in function 'updateOutput'
	/home/flyn/torch/install/share/lua/5.1/rnn/Sequencer.lua:53: in function </home/flyn/torch/install/share/lua/5.1/rnn/Sequencer.lua:34>
	[C]: in function 'xpcall'
	/home/flyn/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/flyn/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./seq2seq.lua:87: in function 'eval'
	eval.lua:55: in function 'say'
	eval.lua:69: in main chunk
	[C]: in function 'dofile'
	...flyn/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/flyn/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/flyn/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./seq2seq.lua:87: in function 'eval'
	eval.lua:55: in function 'say'
	eval.lua:69: in main chunk
	[C]: in function 'dofile'
	...flyn/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```

**Comment by fengmao31** [comment]
i have the bug too

**Comment by Jeavy** [comment]
Hi, I've trained a model with  "th train.lua --cuda --dataset 50000 --hiddenSize 1000" and after that, I got same error as @ArashHosseini (Wrong size for view) when tried to chat. 
Does anyone know how to fix it?
Thanks for help.

**Comment by ghost** [comment]
I found a simple solution. Try this.
In the file seq2seq.lua line 87, change
`local prediction = self.decoder:forward(torch.Tensor(output))[#output]`
to
`local prediction = self.decoder:forward(torch.Tensor({output}):t())[#output][1]`

**Comment by ArashHosseini** [comment]
@Tak-o-m  great report, can also agree.
